import os
import pyautogui
import time


#File module to create a file into current folder
f = open("AutoGenerated_File.txt", "x")
f.close()

#OS module to open the file from current folder
time.sleep(2)
os.startfile(r'AutoGenerated_File.txt')

time.sleep(3)
pyautogui.write('Hello There, This is python file for automate key control', interval = 0.1)

#Short cut key to save
pyautogui.hotkey('ctrl', 'S')

# #File name
# pyautogui.write('example.txt', interval = 0.1)

#to save
pyautogui.press('enter')

#to save
pyautogui.press('left')

#to save
pyautogui.press('enter')